### ISSUE TITLE
HangfireJobIdEnricher is missing in Serilog startup configuration

### ISSUE THREAD

**Issue by TraceLD** [viceroypenguin/VsaTemplate#74]
`HangfireJobIdEnricher` is not registered with Serilog in:
https://github.com/viceroypenguin/VsaTemplate/blob/c21bb03f01dea994f53033d98d44d71cdb71c8b8/Web/Infrastructure/Startup/StartupExtensions.cs#L24

and:
https://github.com/viceroypenguin/VsaTemplate/blob/c21bb03f01dea994f53033d98d44d71cdb71c8b8/Api/Infrastructure/Startup/StartupExtensions.cs#L25

as a result it will not work properly. It should be added via `.Enrich.With<HangfireJobIdEnricher>()`.

**Comment by viceroypenguin** [comment]
Fixed with #5927d35
